#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

fcitx -d &
dunst &
sxhkd &
xcompmgr &
unclutter &
gitwatch $ARSETUP &
# onedrive --syncdir ~/OneDrive --monitor &
 
if [[ $(iseink) -eq 1 ]];then
    eink 
else
    laptop 
fi

xset r rate 220 60
xset s noblank
exec i3
exec xscreensaver --no-splash &
